upstream financas_backend_upstream {
    server financas_backend:9000;
}

server {
    listen 80;
    server_name rafaelsolucoesdigitais.com.br www.rafaelsolucoesdigitais.com.br;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
        autoindex on;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name rafaelsolucoesdigitais.com.br www.rafaelsolucoesdigitais.com.br;

    ssl_certificate /etc/letsencrypt/live/rafaelsolucoesdigitais.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rafaelsolucoesdigitais.com.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/html/public;
    index index.php index.html;

    access_log /var/log/nginx/financas_access.log;
    error_log /var/log/nginx/financas_error.log warn;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass financas_backend_upstream;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # # Cache de arquivos estáticos
    # location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
    #     expires 30d;
    #     access_log off;
    # }

    # # Bloquear acesso a arquivos ocultos (.git, .env etc.)
    # location ~ /\. {
    #     deny all;
    # }
    # Bloquear acesso a arquivos ocultos, EXCETO .well-known
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
